version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/taiga-docker/
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 5000
      runas: root
