version: 0.0
os: linux
files:
  - source: .
    destination: /home/taiga-ec2-user/taiga-docker/
hooks:
  AfterInstall:
    - location: setup.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: run.prod.sh
      timeout: 5000
      runas: root
